---
title: "Conditional Copulas in Elif2011"
output: pdf_document
---


## Conditional Clayton copula


```{r}
n=500
U1=runif(n)
V=runif(n)

X=seq(2,5, length.out = n)
kendallTau=rep(0,n)
U2=rep(0,n)
for (i in 1:n) {
  theta=exp(2 - 0.3*(X[i] - 4)^2)
  kendallTau[i]=theta/(theta+2)
  
  U2[i]=(U1[i]^(-theta)*(V[i]^(-theta/(1+theta))+1))^(-1/theta)
}

par(mfrow=c(1,3))
plot(U1[1:(1/3*n)], U2[1:(1/3*n)], xlab = 'U1', ylab='U2', main = '2<x<-3')
plot(U1[(1/3*n):(2/3*n)], U2[(1/3*n):(2/3*n)],xlab = 'U1', ylab='U2', main = '3<x<4')
plot(U1[(2/3*n):n], U2[(2/3*n):n], xlab = 'U1', ylab='U2', main = '4<x<5')
par(mfrow=c(1,1))
plot(X, kendallTau, type='l')
```


## Conditional Frank copula

```{r}
n=500
U1=runif(n)
V=runif(n)

X=seq(2,5, length.out = n)

fun=function(t){
  t/(exp(t)-1)
}

D=function(theta){
  1/theta*integrate(fun, 0, theta)$value
}
kendallTau=rep(0,n)
U2=rep(0,n)
for (i in 1:n) {
  theta=exp(0.8*X[i] - 2)
  kendallTau[i]=1+4/theta*(D(theta)-1)
  
  U2[i]=-1/theta*log(
    1+(V[i]*(1-exp(-theta)))/
      (V[i]*(exp(-theta*U1[i])-1)-exp(-theta*U1[i]))
                     )
}

par(mfrow=c(1,3))
plot(U1[1:(1/3*n)], U2[1:(1/3*n)], xlab = 'U1', ylab='U2', main = '2<x<-3')
plot(U1[(1/3*n):(2/3*n)], U2[(1/3*n):(2/3*n)],xlab = 'U1', ylab='U2', main = '3<x<4')
plot(U1[(2/3*n):n], U2[(2/3*n):n], xlab = 'U1', ylab='U2', main = '4<x<5')
par(mfrow=c(1,1))
plot(X, kendallTau, type='l')
```