---
title: "Summary of Mohamad Khaled"
output: pdf_document
---

```{r setup, include=FALSE}
library("ggplot2")
library("mixtools")
library("mvtnorm")
library("reshape")
```

## The Copula Example in Mohamad Khaled 2018

This copula is neighter radially symmetric nor exchangeable.

```{r}
R=6
mu=c(-9, -5.4, -1.8, 1.8, 5.4, 9)
sigmar=rep(1/sqrt(10), R)
pi=rep(1/R, R)
alpha=3/4
beta=1/2
theta=20
```


```{r }

# evaluate the function at the point x, where the components 
# of the mixture have weights w, means stored in u, and std deviations
# stored in s - all must have the same length.
F = function(x,w,u,s) sum( w*pnorm(x,mean=u,sd=s) )

# provide an initial bracket for the quantile. default is c(-1000,1000). 
F_inv = function(p,w,u,s,br=c(-1000,1000))
{
  G = function(x) F(x,w,u,s) - p
  return( uniroot(G,br)$root ) 
}

```


```{r}
V=runif(1000)
W=runif(1000)

C <- function(u) {
  (1-beta)*u^(1-alpha)*v^(-beta)*(u^(-theta*alpha)+v^(-theta*beta)-1)^(-1/theta)+
    beta*u^(1-alpha)*v^(-beta*(1+theta))*(u^(-theta*alpha)+v^(-theta*beta)-1)^(-1/theta-1)-w
}

U=rep(0,1000)
for (i in 1:1000) {
  v=V[i]
  w=W[i]
  U[i]=uniroot(C, lower = 0, upper = 1)$root
}

X1=sapply(V, F_inv, w=pi, u=mu, s=sigmar)
X2=sapply(U, F_inv, w=pi, u=mu, s=sigmar)
X=data.frame(X1, X2)

copula=data.frame(V, U)
# write.csv(data, "UV.csv", row.names = FALSE)



```

## EM algorithm to estimate a mixture of multivariate normal distributions

```{r}
Z=qnorm(U);
W=qnorm(V);
dataZ=data.frame(Z, W)

est=mvnormalmixEM(dataZ, lambda = NULL, mu = NULL, sigma = NULL, k = 3,
              arbmean = TRUE, arbvar = TRUE, epsilon = 1e-08, 
              maxit = 10000, verb = FALSE)


```

##Sampling from the posterior predictive distribution

```{r}
x.1<-rmvnorm(round(est$lambda[1],2)*1000, est$mu[[1]], est$sigma[[1]])
x.2 <- rmvnorm(round(est$lambda[2],2)*1000, est$mu[[2]], est$sigma[[2]])
x.3 <-rmvnorm(round(est$lambda[3],2)*1000, est$mu[[3]], est$sigma[[3]])

X.pred <- rbind(x.1, x.2, x.3)
pred=data.frame(X.pred)
colnames(pred)=c("Z", "W")

copula.pred=data.frame(pnorm(pred$W), pnorm(pred$Z))
colnames(copula.pred)=c("V", "U")

```

## Plots of the Copula

```{r}
plotdata1=data.frame(copula, )
ggplot(copula) +
  geom_point(aes(x=V,y=U, color='blue'))+
  geom_point(data=copula.pred,aes(x=V,y=U, color = 'red')) +
  scale_color_discrete(name='', labels=c('Pred','Raw data'))

```



